backend:
  name: github
  repo: abattenburg/netlify-vue-boilerplate
  branch: master # Branch to update
  publish_mode: editorial_workflow
  media_folder: "static/images"

  collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection